<a href="https://colab.research.google.com/github/subashkatwal/Machine_Learning_algorithms/blob/master/PCA_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
np.random.seed(23)

np.random.seed(23)

mu_vec1= np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample= np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df=pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target']=1


mu_vec2= np.array([1,1,1])
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample= np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df1=pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target']= 0

df= df._append(df1,ignore_index= True)
df = df.sample(40)

print(df.head())






    feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148     0.0
34 -0.822939 -1.598109  0.226512     NaN
14  0.420623  0.411620 -0.071324     0.0
11  1.968435 -0.547788 -0.679418     0.0
12 -2.506230  0.146960  0.606195     0.0


#Plotting the 3D model

In [ ]:
import plotly.express as px

In [ ]:

fig= px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],
                   color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGray')),
                  selector=dict(mode='markers'))

fig.show()


#Step 1 Applying standard scale

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

#Step 2 Covarivance matrix

In [ ]:
covariance_matrix= np.cov([df.iloc[:,1],df.iloc[:,2],df.iloc[:,2]])
print('Covariance matrix: \n', covariance_matrix)

Covariance matrix: 
 [[ 1.02564103 -0.15241116 -0.15241116]
 [-0.15241116  1.02564103  1.02564103]
 [-0.15241116  1.02564103  1.02564103]]


#Step 3 : Finding eigen values and eigen vectors

In [ ]:
eigen_values, eigen_vector = np.linalg.eig(covariance_matrix)

In [ ]:
eigen_values

array([ 9.82185346e-01,  2.09473773e+00, -1.89229602e-32])

#Step 4 : Plotting them in 3D space

In [ ]:

%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vector.T:
    a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

Populating the interactive namespace from numpy and matplotlib


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>